### ISSUE TITLE
Publish the plugin

### ISSUE THREAD

**Issue by robb1e** [guardian/sbt-jasmine-plugin#12]
Can you please publish this to the Guardian maven repo?

**Comment by philwills** [comment]
As we're not using this any more, I'm loathe to publish it under our organisation to the SBT plugins repo.

**Comment by robb1e** [comment]
Not testing anymore? Sad face.

**Comment by theefer** [comment]
We still do testing, of course, but we use JavaScript-native tools for that
instead, lately Jasmine via Karma, called from Grunt (or maybe soon
Plumber). We call grunt tasks from sbt using the sbt-grunt-plugin instead.

I'd really recommend that over sbt-jasmine-plugin nowadays...

## Please consider the environment before printing this email.

Visit theguardian.com   

On your mobile, download the Guardian iPhone app theguardian.com/iphone and our iPad edition theguardian.com/iPad  
Save up to 33% by subscribing to the Guardian and Observer - choose the papers you want and get full digital access.
Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also
be privileged. If you are not the named recipient, please notify
the sender and delete the e-mail and all attachments immediately.
Do not disclose the contents to another person. You may not use
the information for any purpose, or store, or copy, it in any way.

Guardian News & Media Limited is not liable for any computer
viruses or other material transmitted with or as part of this
e-mail. You should employ virus checking software.

Guardian News & Media Limited

A member of Guardian Media Group plc
Registered Office
PO Box 68164
Kings Place
90 York Way
London
N1P 2AP

Registered in England Number 908396

---

**Comment by robb1e** [comment]
@theefer I'm just giving @philwills shit
