### ISSUE TITLE
errors while using jasmine-gen-runner

### ISSUE THREAD

**Issue by ebelanger** [guardian/sbt-jasmine-plugin#3]
define is not defined in test-dependencies.js
require is not defined in task.spec.js

This is when using the jasmine-gen-runner from the sbt-jasmine-exemple projet.

**Comment by theefer** [comment]
I fixed the problem both in sbt-jasmine-plugin and sbt-jasmine-example, please try again and let me know if it fixed it for you.

**Comment by ebelanger** [comment]
Thank you very much :)  That was really fast and now it works perfectly.
