### ISSUE TITLE
Missing information that only tests named *spec.js are taken into account

### ISSUE THREAD

**Issue by tdziurko** [guardian/sbt-jasmine-plugin#4]
I've spent few hours trying to figure out why my test setup does not see tests lying in a proper directory and finally after looking into source code I found that this problematic line:

val specsDir = testRoot / "specs" *\* "*spec.js"

It would be much better and clearer if this condition on naming convention could be mentioned in a readme file.

**Comment by anovstrup** [comment]
I just lost an hour or so over this issue as well. Please resolve!

**Comment by joescii** [comment]
I likewise hit this problem.  It is now documented at its [new home](https://github.com/barnesjd/sbt-jasmine-plugin).  Let me know if you think it could be improved.

**Comment by tdziurko** [comment]
Looks good! Thank you :)
